apiVersion: v2
name: microservice-achievements
type: application
version: 0.0.0
appVersion: 0.0.0-rc
description: "microservice-achievements: Achievement microservice."
icon: https://avatars.githubusercontent.com/u/64909001
sources:
  - https://github.com/Ubivius/microservice-achievements
maintainers:
  - name: Ubivius
    email: ubivius@gmail.com
engine: gotpl
